# Generated by Django 4.2.7 on 2023-11-27 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='blog',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='blogApp.blog'),
            preserve_default=False,
        ),
    ]
