# Generated by Django 4.2.7 on 2023-11-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('Dairy', 'Dairy'), ('PantryStaples', 'Pantrystaples'), ('Snacks', 'Snacks'), ('Candy', 'Candy'), ('Bakery', 'Bakery'), ('Beverages', 'Beverages'), ('Chocolate', 'Chocolate')], max_length=200)),
            ],
        ),
    ]
