# Generated by Django 4.2.7 on 2023-11-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapblog', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
