# Generated by Django 4.2.7 on 2023-11-28 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_op', '0006_published_blog_content_published_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('published', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_op.published')),
            ],
        ),
    ]
