# Generated by Django 4.2.7 on 2023-12-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Makeup', 'Makeup'), ('Movie', 'Movie'), ('Celebrities', 'Celebrities'), ('Care', 'Care'), ('Places', 'Places')], max_length=50),
        ),
    ]
