# Generated by Django 4.2.7 on 2023-11-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
    ]
