# Generated by Django 4.2.7 on 2023-12-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linkedin_link',
            new_name='instagram_link',
        ),
    ]
