# Generated by Django 4.2.7 on 2023-11-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_info_category_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='category',
            field=models.CharField(choices=[('Photo', 'Photo'), ('Video', 'Video'), ('Other', 'Other')], default='Other', max_length=64),
        ),
    ]
