# Generated by Django 4.2.7 on 2023-11-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
